version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
  alembic:
    build:
      context: .
    command: sh -c "alembic upgrade head"
    volumes:
      - .:/app
    depends_on:
      - postgres
